config/routes.rb
Rails.application.routes.draw do
  resources :nodes
  devise_for :users
  resources :events
  resources :indicators
  root 'generator#home'
  post '/', to: 'generator#create', as: 'generator_create'
  post '/sensor', to: 'generator#sensor', as: 'generator_sensor'
end

app/models/node.rb
class Node < ApplicationRecord
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        # Create Node in Fabric
        `curl -s -X POST --header 'Content-Type: application/json' \
        --header 'Accept: application/json' 'http://localhost:3000/api/Node' \
        -d '{ \
            "$class": "org.fyp.teddib.Node", \
            "mac": "#{@node.mac}", \
            "stateValue": "0", \
            "owner": "resource:org.fyp.teddib.User#1" \
        }'`
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    `curl -s -X DELETE --header 'Accept: application/json' "http://localhost:3000/api/Node/#{@node.mac}"`
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:name, :state, :mac)
    end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_with(model: node, local: true) do |form| %>
  <% if node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :node_name %>
  </div>

  <div class="field">
    <%= form.label :mac %>
    <%= form.text_field :mac, id: :node_mac %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form', node: @node %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Mac</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.name %></td>
        <td><%= node.state %></td>
        <td><%= node.mac %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td> | 
          <% node.state.each_char.with_index do |e, i| %>
            <% if e == '1' %>
              <%= Indicator.find_by_id(i+1).name %><% if i < node.state.size-1 %>,<% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New Node</h1>

<%= render 'form', node: @node %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @node.state %>
</p>

<p>
  <strong>Mac:</strong>
  <%= @node.mac %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>