config/routes.rb
Rails.application.routes.draw do
  resources :nodes
  devise_for :users
  resources :events
  resources :indicators
  root 'generator#home'
  post '/', to: 'generator#create', as: 'generator_create'
  post '/sensor', to: 'generator#sensor', as: 'generator_sensor'
end

app/models/indicator.rb
class Indicator < ApplicationRecord
end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_indicator, only: [:show, :edit, :update, :destroy]

  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = Indicator.all
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
  end

  # GET /indicators/new
  def new
    @indicator = Indicator.new
  end

  # GET /indicators/1/edit
  def edit
  end

  # POST /indicators
  # POST /indicators.json
  def create
    @indicator = Indicator.new(indicator_params)

    respond_to do |format|
      if @indicator.save
        format.html { redirect_to @indicator, notice: 'Indicator was successfully created.' }
        format.json { render :show, status: :created, location: @indicator }
      else
        format.html { render :new }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1
  # PATCH/PUT /indicators/1.json
  def update
    respond_to do |format|
      if @indicator.update(indicator_params)
        format.html { redirect_to @indicator, notice: 'Indicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator }
      else
        format.html { render :edit }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator.destroy
    respond_to do |format|
      format.html { redirect_to indicators_url, notice: 'Indicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator
      @indicator = Indicator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_params
      params.require(:indicator).permit(:name, :start_value, :end_value)
    end
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/views/indicators/_form.html.erb
<%= form_with(model: indicator, local: true) do |form| %>
  <% if indicator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indicator.errors.count, "error") %> prohibited this indicator from being saved:</h2>

      <ul>
      <% indicator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :indicator_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/indicators/edit.html.erb
<h1>Editing Indicator</h1>

<%= render 'form', indicator: @indicator %>

<%= link_to 'Show', @indicator %> |
<%= link_to 'Back', indicators_path %>

app/views/indicators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indicators</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indicators.each do |indicator| %>
      <tr>
        <td><%= indicator.id %></td>
        <td><%= indicator.name %></td>
        <td><%= link_to 'Show', indicator %></td>
        <td><%= link_to 'Edit', edit_indicator_path(indicator) %></td>
        <td><%= link_to 'Destroy', indicator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indicator', new_indicator_path %>

app/views/indicators/new.html.erb
<h1>New Indicator</h1>

<%= render 'form', indicator: @indicator %>

<%= link_to 'Back', indicators_path %>

app/views/indicators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @indicator.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @indicator.name %>
</p>

<%= link_to 'Edit', edit_indicator_path(@indicator) %> |
<%= link_to 'Back', indicators_path %>